module.exports = {
	siteUrl: 'https://omnifinery.com',
	generateRobotsTxt: true, // (optional)
	// ...other options
	exclude: [
		'/sitemaps/editorials/0.xml',
		'/sitemaps/editorials/1.xml',
		'/sitemaps/editorials/2.xml',
		'/sitemaps/editorials/3.xml',
		'/sitemaps/editorials/4.xml',
		'/sitemaps/editorials/5.xml',
		'/sitemaps/editorials/6.xml',
		'/sitemaps/editorials/7.xml',
		'/sitemaps/editorials/8.xml',

		'/sitemaps/products/0.xml',
		'/sitemaps/products/1.xml',
		'/sitemaps/products/2.xml',
		'/sitemaps/products/3.xml',
		'/sitemaps/products/4.xml',
		'/sitemaps/products/5.xml',
		'/sitemaps/products/6.xml',
		'/sitemaps/products/7.xml',
		'/sitemaps/products/8.xml',
		'/sitemaps/products/9.xml',
		'/sitemaps/products/10.xml',
		'/sitemaps/products/11.xml',
	], // <= exclude here
	robotsTxtOptions: {
		additionalSitemaps: [
			'https://omnifinery.com/sitemaps/editorials/0.xml',
			'https://omnifinery.com/sitemaps/editorials/1.xml',
			'https://omnifinery.com/sitemaps/editorials/2.xml',
			'https://omnifinery.com/sitemaps/editorials/3.xml',
			'https://omnifinery.com/sitemaps/editorials/4.xml',
			'https://omnifinery.com/sitemaps/editorials/5.xml',
			'https://omnifinery.com/sitemaps/editorials/6.xml',
			'https://omnifinery.com/sitemaps/editorials/7.xml',
			'https://omnifinery.com/sitemaps/editorials/8.xml',

			'https://omnifinery.com/sitemaps/products/0.xml',
			'https://omnifinery.com/sitemaps/products/1.xml',
			'https://omnifinery.com/sitemaps/products/2.xml',
			'https://omnifinery.com/sitemaps/products/3.xml',
			'https://omnifinery.com/sitemaps/products/4.xml',
			'https://omnifinery.com/sitemaps/products/5.xml',
			'https://omnifinery.com/sitemaps/products/6.xml',
			'https://omnifinery.com/sitemaps/products/7.xml',
			'https://omnifinery.com/sitemaps/products/8.xml',
			'https://omnifinery.com/sitemaps/products/9.xml',
			'https://omnifinery.com/sitemaps/products/10.xml',
			'https://omnifinery.com/sitemaps/products/11.xml',
		],
	},
};
